class RemoteError(Exception):
    pass

class LocalError(Exception):
    pass
